import type { StreamerChannel } from "./types";

export const STREAMER_CHANNELS: StreamerChannel[] = [
  {
    id: "fakmon-gg",
    name: "Fakmon GG",
    channelId: "UCHYWsJ6Dz8PuOeIlNEZAw8A",
    channelUrl: "https://youtube.com/@FakmonGG",
  },
  {
    id: "andrew-bahvana",
    name: "Andrew Bahvana",
    channelId: "UCVdtzRGwTOoz_PnZgA_jWWQ",
    channelUrl: "https://www.youtube.com/@ANDREWBAHVANA",
  },
  {
    id: "alz-verse",
    name: "Alz Verse",
    channelId: "UCBdVHpZS8CQW9giX5RSe09A",
    channelUrl: "https://www.youtube.com/@Alz_Verse",
  },
  {
    id: "radvondo",
    name: "Radvondo",
    channelId: "UCdsffZziX1N_B8nDMc7SlCQ",
    channelUrl: "https://www.youtube.com/@radvondo",
  },
  {
    id: "ojiiez",
    name: "Ojii Ez",
    channelId: "UCtrw52yTN_FaVeY4_UDIY7g",
    channelUrl: "https://www.youtube.com/@OjiiEz",
  },
  {
    id: "zadolfsky",
    name: "Zadolfsky",
    channelId: "UCRfnxg74-yBlKm07DiBK9MQ",
    channelUrl: "https://www.youtube.com/@zadolfsky",
  },
  {
    id: "hanekkk",
    name: "Hanekkk",
    channelId: "UCt3x5nMhSm8jBrQ4DiH1LJA",
    channelUrl: "https://www.youtube.com/@hanekkk",
  },
  {
    id: "baby-quinnn",
    name: "Baby Quinnn",
    channelId: "UCFiMRXqdFQ15Nk2Zvg-VcOQ",
    channelUrl: "https://www.youtube.com/@BabyQuinnn",
  },
  {
    id: "farrasarrafii",
    name: "Farrasarrafii",
    channelId: "UCVNmamDy7EEFeLD-56hAPmQ",
    channelUrl: "https://www.youtube.com/@farrasarrafii",
  },
  {
    id: "andooee",
    name: "Andooee",
    channelId: "UC6sNcRL0K5SpTJ0HAJqnkWg",
    channelUrl: "https://www.youtube.com/@andooee",
  },
  {
    id: "rotipunya",
    name: "Rotipunya",
    channelId: "UCxE_pSfxW9cwmZm-NSn281w",
    channelUrl: "https://www.youtube.com/@Rotipunya",
  },
  {
    id: "edward-caspian",
    name: "Edward Caspian",
    channelId: "UCnZbg03QJSc37PWezlxPmgA",
    channelUrl: "https://www.youtube.com/@EdwardCaspian",
  },
  {
    id: "poufles",
    name: "Poufles",
    channelId: "UCRKOD4hw4jKhavak4cTDz6g",
    channelUrl: "https://www.youtube.com/@poufles",
  },
  {
    id: "miraclee-zxc",
    name: "Miraclee ZXC",
    channelId: "UCkvtvlYyemyBeDjuhJaU5qg",
    channelUrl: "https://www.youtube.com/@miraclee-zxc",
  },
  {
    id: "mikey-teller-mt",
    name: "Mikey Teller MT",
    channelId: "UCtf8Krw5QiTcPk1OhZGSRSw",
    channelUrl: "https://www.youtube.com/@Mikey_TellerMT",
  },
  {
    id: "l3nsss",
    name: "L3nsss",
    channelId: "UCdDTzrkukGFJttagbmqdWUg",
    channelUrl: "https://www.youtube.com/@L3nsss",
  },
  {
    id: "e1zannnn00",
    name: "E1zannnn00",
    channelId: "UC2595FgudjMrThCAFA0F3Wg",
    channelUrl: "https://www.youtube.com/@e1zannnn00",
  },
  {
    id: "jessicaprashela",
    name: "Jessica Prashela",
    channelId: "UCH_8FYTGTcnuEsyDYzszlWg",
    channelUrl: "https://www.youtube.com/@jessicaprashela",
  },
  {
    id: "ajaxynf",
    name: "Ajaxynf",
    channelId: "UCYzFzyj2P8ANs8evXEgVueA",
    channelUrl: "https://www.youtube.com/@ajaxynf",
  },
  {
    id: "honeyyellowbee",
    name: "Honey Yellow Bee",
    channelId: "UCDq0m2i9_1ZauikosjKTNJw",
    channelUrl: "https://www.youtube.com/@honeyyellowbee",
  },
  {
    id: "tebehihi27",
    name: "Tebehihi 27",
    channelId: "UCyrrfEryy8-jPKCyqWdV6qA",
    channelUrl: "https://www.youtube.com/@tebehihi27",
  },
  {
    id: "isalonica",
    name: "Isalonica",
    channelId: "UCRJzcqYHhn_UtAXVAnNlu4Q",
    channelUrl: "https://www.youtube.com/@isalonica",
  },
  {
    id: "aldohms",
    name: "Aldohms",
    channelId: "UCGWdDu9JAye_cFZYh-NKZmQ",
    channelUrl: "https://www.youtube.com/@aldohms",
  },
  {
    id: "broklyn-scott",
    name: "Broklyn Scott",
    channelId: "UCdUdVhhg3zfQ9rrzf3WRFUg",
    channelUrl: "https://www.youtube.com/@Broklyn-Scott",
  },
  {
    id: "amoreken",
    name: "Amoreken",
    channelId: "UCQBAeFSWgjL6cXQJJG5ARHA",
    channelUrl: "https://www.youtube.com/@amoreken",
  },
  {
    id: "arzemeowmeow",
    name: "Arze Meow Meow",
    channelId: "UCfN5RUgo7nBCisQn0-cPOYg",
    channelUrl: "https://www.youtube.com/@arzemeowmeow",
  },
  {
    id: "aevnyx",
    name: "Aevnyx",
    channelId: "UC3r_PvlnOeVKzELCvvVaU0Q",
    channelUrl: "https://www.youtube.com/@aevnyx",
  },
  {
    id: "jamalinsom",
    name: "Jamal Insom",
    channelId: "UCbSdqr9TF1JYWd8crKKoGIg",
    channelUrl: "https://www.youtube.com/@jamalinsom",
  },
  {
    id: "xinceeedotexe",
    name: "Xinceee Dot Exe",
    channelId: "UC7p8Ro16hIUqCoy1GhmBGWQ",
    channelUrl: "https://www.youtube.com/@Xinceeedotexe",
  },
  {
    id: "abizzaaditya",
    name: "Abizza Aditya",
    channelId: "UCN6OM5Mw-VhWjrXyAfbSyLg",
    channelUrl: "https://www.youtube.com/@abizzaaditya",
  },
  {
    id: "mogiimogicha",
    name: "Mogii Mogicha",
    channelId: "UCDpjs1i8IbCDQesdICvzTYw",
    channelUrl: "https://www.youtube.com/@MogiiMogicha",
  },
  {
    id: "rivaldstn",
    name: "Rivaldstn",
    channelId: "UC0_2iDbA4sKEAyvznPxo5eQ",
    channelUrl: "https://www.youtube.com/@rivaldstn_",
  },
  {
    id: "putrirp",
    name: "Putrirp",
    channelId: "UCDZBa4bFbYWt_1gYAam2F6w",
    channelUrl: "https://www.youtube.com/@putrirp",
  },
  {
    id: "zaeikiy3163",
    name: "Zaeikiy 3163",
    channelId: "UCKlKsyvzLMlqg40Zo6AcwrQ",
    channelUrl: "https://www.youtube.com/@zaeikiy3163",
  },
  {
    id: "ipinmendes",
    name: "Ipin Mendes",
    channelId: "UCut3LFU2pUS1LfI5-qYnIHw",
    channelUrl: "https://www.youtube.com/@ipinmendes",
  },
  {
    id: "kidnapping",
    name: "Kidnapping",
    channelId: "UCH7Xe5ricGK8dufrkr8nqzg",
    channelUrl: "https://www.youtube.com/@kidnapping.",
  },
  {
    id: "nangdine",
    name: "Nangdine",
    channelId: "UCNldXnwD-G0mWbZeYDyWMQw",
    channelUrl: "https://www.youtube.com/@nangdine",
  },
  {
    id: "mozzaaa",
    name: "Mozzaaa",
    channelId: "UCSRE1yFJ0v4d9rgGdF3L5vQ",
    channelUrl: "https://www.youtube.com/@Mozzaaa_",
  },
  {
    id: "damnthiskay",
    name: "Damn This Kay",
    channelId: "UCKTV1i11yUA-RgmpsvUDYPg",
    channelUrl: "https://www.youtube.com/@DamnThiskay",
  },
  {
    id: "aurornirvana",
    name: "Auror Nirvana",
    channelId: "UCGvFE-3QT94eqsbbXsqhefg",
    channelUrl: "https://www.youtube.com/@aurornirvana",
  },
  {
    id: "island-boy-gg",
    name: "Island Boy GG",
    channelId: "UCc8rh0l91jw86wz8m2o6Dbw",
    channelUrl: "https://www.youtube.com/@IslandBoyGG",
  },
  {
    id: "rafli-saftari",
    name: "Rafli Saftari",
    channelId: "UCANFCkEP5Z5-kFBA5bJ6mOQ",
    channelUrl: "https://www.youtube.com/@RafliSaftari",
  },
  {
    id: "islee10",
    name: "Islee 10",
    channelId: "UCWADr8HQw65jZ5dBMTGm-lg",
    channelUrl: "https://www.youtube.com/@Islee10",
  },
  {
    id: "venesiavenee",
    name: "Venesia Venee",
    channelId: "UCtfax45apiFZvZTwgD4lP-A",
    channelUrl: "https://www.youtube.com/@venesiavenee",
  },
  {
    id: "pakdimm",
    name: "Pakdimm",
    channelUrl: "https://www.youtube.com/@Pakdimm",
  },
  {
    id: "poppy-capiii",
    name: "Poppy Capiii",
    channelId: "UCMwQ7uTUXO5Q3P8nDYsoR8A",
    channelUrl: "https://www.youtube.com/channel/UCMwQ7uTUXO5Q3P8nDYsoR8A",
  },
  {
    id: "liyon",
    name: "Liyon",
    channelId: "UCuMuq1gINc_t-GfJtXXcyXw",
    channelUrl: "https://www.youtube.com/channel/UCuMuq1gINc_t-GfJtXXcyXw",
  },
  {
    id: "aang-mahesa",
    name: "Aang Mahesa",
    channelUrl: "https://youtube.com/@aangmahesa047",
  },
  {
    id: "ucup-pablo",
    name: "Ucup Pablo",
    channelUrl: "https://youtube.com/@ucuppablo",
  },
  {
    id: "mat4-ggg",
    name: "Mat4 GGG",
    channelUrl: "https://www.youtube.com/@Mat4GGG",
  },
];

export function getStreamerInitial(name: string): string {
  return name.trim().charAt(0).toUpperCase() || "?";
}
