import type { StreamerChannel } from "./types";

export const STREAMER_CHANNELS: StreamerChannel[] = [
  {
    id: "fakmon-gg",
    name: "Fakmon GG",
    channelHandle: "@FakmonGG",
    channelUrl: "https://youtube.com/@FakmonGG",
  },
  {
    id: "andrew-bahvana",
    name: "Andrew Bahvana",
    channelHandle: "@ANDREWBAHVANA",
    channelUrl: "https://www.youtube.com/@ANDREWBAHVANA",
  },
  {
    id: "alz-verse",
    name: "Alz Verse",
    channelHandle: "@Alz_Verse",
    channelUrl: "https://www.youtube.com/@Alz_Verse",
  },
  {
    id: "radvondo",
    name: "Radvondo",
    channelHandle: "@radvondo",
    channelUrl: "https://www.youtube.com/@radvondo",
  },
  {
    id: "ojiiez",
    name: "Ojii Ez",
    channelHandle: "@OjiiEz",
    channelUrl: "https://www.youtube.com/@OjiiEz",
  },
  {
    id: "zadolfsky",
    name: "Zadolfsky",
    channelHandle: "@zadolfsky",
    channelUrl: "https://www.youtube.com/@zadolfsky",
  },
  {
    id: "hanekkk",
    name: "Hanekkk",
    channelHandle: "@hanekkk",
    channelUrl: "https://www.youtube.com/@hanekkk",
  },
  {
    id: "baby-quinnn",
    name: "Baby Quinnn",
    channelHandle: "@BabyQuinnn",
    channelUrl: "https://www.youtube.com/@BabyQuinnn",
  },
  {
    id: "farrasarrafii",
    name: "Farrasarrafii",
    channelHandle: "@farrasarrafii",
    channelUrl: "https://www.youtube.com/@farrasarrafii",
  },
  {
    id: "andooee",
    name: "Andooee",
    channelHandle: "@andooee",
    channelUrl: "https://www.youtube.com/@andooee",
  },
  {
    id: "rotipunya",
    name: "Rotipunya",
    channelHandle: "@Rotipunya",
    channelUrl: "https://www.youtube.com/@Rotipunya",
  },
  {
    id: "edward-caspian",
    name: "Edward Caspian",
    channelHandle: "@EdwardCaspian",
    channelUrl: "https://www.youtube.com/@EdwardCaspian",
  },
  {
    id: "poufles",
    name: "Poufles",
    channelHandle: "@poufles",
    channelUrl: "https://www.youtube.com/@poufles",
  },
  {
    id: "miraclee-zxc",
    name: "Miraclee ZXC",
    channelHandle: "@miraclee-zxc",
    channelUrl: "https://www.youtube.com/@miraclee-zxc",
  },
  {
    id: "mikey-teller-mt",
    name: "Mikey Teller MT",
    channelHandle: "@Mikey_TellerMT",
    channelUrl: "https://www.youtube.com/@Mikey_TellerMT",
  },
  {
    id: "l3nsss",
    name: "L3nsss",
    channelHandle: "@L3nsss",
    channelUrl: "https://www.youtube.com/@L3nsss",
  },
  {
    id: "e1zannnn00",
    name: "E1zannnn00",
    channelHandle: "@e1zannnn00",
    channelUrl: "https://www.youtube.com/@e1zannnn00",
  },
  {
    id: "jessicaprashela",
    name: "Jessica Prashela",
    channelHandle: "@jessicaprashela",
    channelUrl: "https://www.youtube.com/@jessicaprashela",
  },
  {
    id: "ajaxynf",
    name: "Ajaxynf",
    channelHandle: "@ajaxynf",
    channelUrl: "https://www.youtube.com/@ajaxynf",
  },
  {
    id: "honeyyellowbee",
    name: "Honey Yellow Bee",
    channelHandle: "@honeyyellowbee",
    channelUrl: "https://www.youtube.com/@honeyyellowbee",
  },
  {
    id: "tebehihi27",
    name: "Tebehihi 27",
    channelHandle: "@tebehihi27",
    channelUrl: "https://www.youtube.com/@tebehihi27",
  },
  {
    id: "isalonica",
    name: "Isalonica",
    channelHandle: "@isalonica",
    channelUrl: "https://www.youtube.com/@isalonica",
  },
  {
    id: "aldohms",
    name: "Aldohms",
    channelHandle: "@aldohms",
    channelUrl: "https://www.youtube.com/@aldohms",
  },
  {
    id: "broklyn-scott",
    name: "Broklyn Scott",
    channelHandle: "@Broklyn-Scott",
    channelUrl: "https://www.youtube.com/@Broklyn-Scott",
  },
  {
    id: "amoreken",
    name: "Amoreken",
    channelHandle: "@amoreken",
    channelUrl: "https://www.youtube.com/@amoreken",
  },
  {
    id: "arzemeowmeow",
    name: "Arze Meow Meow",
    channelHandle: "@arzemeowmeow",
    channelUrl: "https://www.youtube.com/@arzemeowmeow",
  },
  {
    id: "aevnyx",
    name: "Aevnyx",
    channelHandle: "@aevnyx",
    channelUrl: "https://www.youtube.com/@aevnyx",
  },
  {
    id: "jamalinsom",
    name: "Jamal Insom",
    channelHandle: "@jamalinsom",
    channelUrl: "https://www.youtube.com/@jamalinsom",
  },
  {
    id: "xinceeedotexe",
    name: "Xinceee Dot Exe",
    channelHandle: "@Xinceeedotexe",
    channelUrl: "https://www.youtube.com/@Xinceeedotexe",
  },
  {
    id: "abizzaaditya",
    name: "Abizza Aditya",
    channelHandle: "@abizzaaditya",
    channelUrl: "https://www.youtube.com/@abizzaaditya",
  },
  {
    id: "mogiimogicha",
    name: "Mogii Mogicha",
    channelHandle: "@MogiiMogicha",
    channelUrl: "https://www.youtube.com/@MogiiMogicha",
  },
  {
    id: "rivaldstn",
    name: "Rivaldstn",
    channelHandle: "@rivaldstn_",
    channelUrl: "https://www.youtube.com/@rivaldstn_",
  },
  {
    id: "putrirp",
    name: "Putrirp",
    channelHandle: "@putrirp",
    channelUrl: "https://www.youtube.com/@putrirp",
  },
  {
    id: "zaeikiy3163",
    name: "Zaeikiy 3163",
    channelHandle: "@zaeikiy3163",
    channelUrl: "https://www.youtube.com/@zaeikiy3163",
  },
  {
    id: "ipinmendes",
    name: "Ipin Mendes",
    channelHandle: "@ipinmendes",
    channelUrl: "https://www.youtube.com/@ipinmendes",
  },
  {
    id: "kidnapping",
    name: "Kidnapping",
    channelHandle: "@kidnapping.",
    channelUrl: "https://www.youtube.com/@kidnapping.",
  },
  {
    id: "nangdine",
    name: "Nangdine",
    channelHandle: "@nangdine",
    channelUrl: "https://www.youtube.com/@nangdine",
  },
  {
    id: "mozzaaa",
    name: "Mozzaaa",
    channelHandle: "@Mozzaaa_",
    channelUrl: "https://www.youtube.com/@Mozzaaa_",
  },
  {
    id: "damnthiskay",
    name: "Damn This Kay",
    channelHandle: "@DamnThiskay",
    channelUrl: "https://www.youtube.com/@DamnThiskay",
  },
  {
    id: "aurornirvana",
    name: "Auror Nirvana",
    channelHandle: "@aurornirvana",
    channelUrl: "https://www.youtube.com/@aurornirvana",
  },
  {
    id: "island-boy-gg",
    name: "Island Boy GG",
    channelHandle: "@IslandBoyGG",
    channelUrl: "https://www.youtube.com/@IslandBoyGG",
  },
  {
    id: "rafli-saftari",
    name: "Rafli Saftari",
    channelHandle: "@RafliSaftari",
    channelUrl: "https://www.youtube.com/@RafliSaftari",
  },
  {
    id: "islee10",
    name: "Islee 10",
    channelHandle: "@Islee10",
    channelUrl: "https://www.youtube.com/@Islee10",
  },
  {
    id: "venesiavenee",
    name: "Venesia Venee",
    channelHandle: "@venesiavenee",
    channelUrl: "https://www.youtube.com/@venesiavenee",
  },
];

export function getStreamerInitial(name: string): string {
  return name.trim().charAt(0).toUpperCase() || "?";
}
